# Generated by Django 4.0.4 on 2022-04-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='list_of_words',
        ),
    ]
